export const CHANGE_FELIDS = 'CHANGE_FELIDS';
export const CHANGE_SIGNATURE = 'CHANGE_SIGNATURE';
export const REPLACE_SPECIFIC_SIGNATURE = 'REPLACE_SPECIFIC_SIGNATURE';
export const ADD_SIGNATURE_LIST = 'ADD_SIGNATURE_LIST';
export const ADD_POSITION = 'ADD_POSITION';
